version: '3.3'

services:

  nginx_proxy:
    image: nginx:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./nginx_proxy/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx_proxy:/var/log/nginx
    restart: always
    ports:
      - 8888:80
    depends_on:
      - nginx
    networks:
      app_net:
        ipv4_address: 10.0.0.5

  nginx:
    image: nginx:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./www/html:/var/www/html
      - ./var/log/nginx:/var/log/nginx
    restart: always
    depends_on:
      - php
    networks:
      app_net:
        ipv4_address: 10.0.0.10  

  php:
    image: php:7.4-fpm
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./www/html:/var/www/html
      - ./php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/config/php.ini-production:/usr/local/etc/php/php.ini
      - ./var/log/php:/var/log/php
    restart: always
    networks:
      app_net:
        ipv4_address: 10.0.0.15

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
